CREATE TABLE projets (
   id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `titre` varchar(128) DEFAULT NULL,
  `categorie` varchar(128) DEFAULT NULL,
  `description` text,
  `details` text,
  `dateprojet` date DEFAULT NULL,
  `client` varchar(128) DEFAULT NULL,
  `url` varchar(256) DEFAULT NULL,
  `thumbnail` varchar(256) DEFAULT NULL,
  `image` varchar(256) DEFAULT NULL,
  `alt` varchar(128) DEFAULT NULL
)


INSERT INTO `projets` (`titre`, `categorie`, `description`, `dateprojet`, `client`, `url`, `thumbnail`, `image`, `alt`, `details`) VALUES
('Restaurant Lambda', 'Site-vitrine', 'Création d\'un site Web & intégration d\'après maquette', '2018-12-01', 'formation Access Code School', 'http://christiana.promo-27.codeur.online/restaurant', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/restaurant-thumbnail.jpg', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/restaurant-full.jpg', 'Site d\'un restaurant lambda', '<p>Ce site a &eacute;t&eacute; cod&eacute; en HTML et CSS en int&eacute;grant un framework. Il s\'agissait d\'un exercice dans le cadre de la formation&nbsp;<strong><em>Access Code School</em></strong>. Ce travail d\'&eacute;quipe a &eacute;t&eacute; accompli en exportant les ressources depuis une maquette Photoshop en collaboration avec <a href=\"https://www.linkedin.com/in/youness-ahadach-120062173/\" target=\"_blank\" rel=\"noopener\"><strong>Youness AHADACH</strong></a>.</p>'),
('Portfolio Blueasy', 'Portfolio', 'Création d\'un site Web & intégration d\'après maquette', '2019-01-01', 'formation Access Code School', 'https://christiana.promo-27.codeur.online/blueasy/', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/blueasy-thumbnail.jpg', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/blueasy-full.jpg', 'Portfolio Blueasy', '<p>Ce site a &eacute;t&eacute; cod&eacute; en HTML et CSS en int&eacute;grant un framework. C\'est un travail accompli en solo pendant la formation&nbsp;<strong><em>Access Code School</em></strong>. Le site a &eacute;t&eacute; r&eacute;alit&eacute; en exportant les ressources depuis une maquette Photoshop.</p>'),
('Virus Invader', 'Jeu', 'Maquettage et intégration d\'un jeu en JavaScript', '2019-01-01', 'formation Access Code School', 'https://christiana.promo-27.codeur.online/JS-Virus-Invader/', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/invader-thumbnail.jpg', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/invader-full.jpg', 'Jeu JavaScript VirusIndader', '<p>Ce jeu en javascript se pr&eacute;sente sur une page web. Il a &eacute;t&eacute; cod&eacute; dans le cadre de la formation&nbsp;<strong><em>Access Code School</em></strong>. Nous avons cr&eacute;&eacute; une maquette design avant de l\'int&eacute;grer en CSS et HTML. En collaboration avec <a href=\"https://www.linkedin.com/in/adrien-boilley-a4225760/\" target=\"_blank\" rel=\"noopener\"><strong>Adrien BOILLEY</strong></a>.</p>'),
('Blog CaféInline', 'Site WordPress', 'Maquettage, création d\'un thème WordPress', '2019-02-02', 'formation Access Code School', 'https://marieanger.promo-27.codeur.online/cafeinline/', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/cafeinline-thumbnail.jpg', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/cafeinline-full.jpg', 'Blog de la promo 27 CaféInline', '<p>Ce blog a &eacute;t&eacute; cr&eacute;&eacute; sur un CMS WordPress pour lequel nous avons cr&eacute;&eacute;s un th&egrave;me original. Il s\'agissait d\'un exercice dans le cadre de la formation&nbsp;<strong><em>Access Code School</em></strong>. Ce travail d\'&eacute;quipe a &eacute;t&eacute; accompli en &eacute;quipe avec <a href=\"https://ghislainb.promo-27.codeur.online/portfolio\" target=\"_blank\" rel=\"noopener\"><strong>Ghislain BILLARD</strong></a> et <a href=\"http://www.marieangeremy.fr\" target=\"_blank\" rel=\"noopener\"><strong>Marie-Ange REMY</strong></a>.</p>'),
('Fanny Cassani', 'Site WordPress', 'Intégration d\'après maquette, création de thème WordPress', '2019-02-25', 'Fanny Cassani', 'https://fannycassani.fr', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/fannycassani-thumbnail.jpg', 'https://christiana.promo-27.codeur.online/blindchrisportfolio/public/img/portfolio/fannycassani-full.jpg', 'Site de Fanny Cassani, paysagiste concepteur', '<p>Le portfolio de la paysagiste Fanny Cassani est bas&eacute; sur WordPress. Il s\'agit de la mise en place d\'un site bas&eacute; sur WordPress suivite d\'une int&eacute;gration de maquette sous forme de th&egrave;me. J\'ai travaill&eacute; au sein du&nbsp;<a href=\"collectif-hedera.fr\" target=\"_blank\" rel=\"noopener\"><strong><em>collectif Hedera</em></strong></a>&nbsp;avec qui se projet a constitu&eacute; une collaboration pendant mon stage.</p>');